/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { Box, MeshDistortMaterial, MeshReflectorMaterial, MeshWobbleMaterial, useGLTF } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import lerp from "lerp";
import { useSpring, animated, config } from "@react-spring/three";

export default function MovingBox({ position, start, end, speed, mouse }) {

  const group = useRef();

  useFrame(
    (state) => (
      (group.current.position.z >= end ? group.current.position.z = start : group.current.position.z += speed),
      (group.current.position.x = -position[0] + mouse.x / 2000),
      (group.current.rotation.y = 0 + -mouse.x / 10000)
      ))

  return (
    <Box ref={group} position={position}>
        <meshBasicMaterial attach="material" color="white" />

        </Box>
  );
}

